# Generated by Django 2.0.1 on 2018-02-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Código')),
                ('model', models.CharField(blank=True, max_length=255, null=True, verbose_name='Modelo Afectado')),
                ('pass_object', models.TextField(blank=True, null=True, verbose_name='Objeto Anterior')),
                ('new_object', models.TextField(blank=True, null=True, verbose_name='Objeto Nuevo')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('user', models.TextField(blank=True, null=True, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'ordering': ['id'],
            },
        ),
    ]
