# Generated by Django 2.0.1 on 2018-02-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_auto_20180221_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
    ]
