# Generated by Django 2.0.1 on 2018-02-23 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_log_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='date',
        ),
    ]
