# Generated by Django 2.0.1 on 2018-01-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180126_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='id_num',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Num Identificación'),
        ),
    ]
