# Generated by Django 2.0.1 on 2018-04-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20180129_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pin',
            field=models.CharField(blank=True, default='0000', max_length=4, null=True, verbose_name='PIN'),
        ),
    ]
