# Generated by Django 2.0.1 on 2018-01-29 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, null=True, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('id_type', models.CharField(choices=[('per', 'Cédula Física'), ('jur', 'Cédula Jurídica'), ('pas', 'Pasaporte')], default='per', max_length=3, verbose_name='Tipo de Identificación')),
                ('id_num', models.CharField(blank=True, max_length=255, null=True, verbose_name='Num Identificación')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Teléfono')),
                ('cellphone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('agent_name', models.CharField(max_length=255, verbose_name='Nombre del Agente')),
                ('agent_last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellidos del Agente')),
                ('agent_phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Teléfono del agente')),
                ('agent_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email del Agente')),
                ('bank_accounts', models.TextField(blank=True, null=True, verbose_name='Cuentas Bancarias')),
                ('sinpe_accounts', models.TextField(blank=True, null=True, verbose_name='Cuentas SINPE')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['code'],
            },
        ),
    ]
