# Generated by Django 2.0.1 on 2018-02-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_auto_20180221_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificación'),
        ),
    ]
