# Generated by Django 2.0.1 on 2018-02-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_auto_20180224_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='agent_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Agente'),
        ),
    ]
