# Generated by Django 2.0.1 on 2018-01-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellidos')),
                ('code', models.CharField(max_length=10, null=True, verbose_name='Código')),
                ('id_type', models.CharField(choices=[('per', 'Cédula Física'), ('jur', 'Cédula Jurídica'), ('pas', 'Pasaporte')], default='per', max_length=3, verbose_name='Tipo de Identificación')),
                ('id_num', models.CharField(blank=True, max_length=255, null=True, verbose_name='Num Identificación')),
                ('has_credit', models.BooleanField(default=False, verbose_name='Tiene Crédito?')),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True, verbose_name='Límite de Crédito')),
                ('debt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True, verbose_name='Saldo')),
                ('credit_days', models.PositiveIntegerField(blank=True, default=30, null=True, verbose_name='Días de Crédito')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id'],
            },
        ),
    ]
