# Generated by Django 2.0.1 on 2018-01-29 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_debt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['code'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddField(
            model_name='client',
            name='adress',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='client',
            name='cellphone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='client',
            name='max_discount',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Descuento Máximo'),
        ),
        migrations.AddField(
            model_name='client',
            name='max_line_discount',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Descuento Máximo por línea'),
        ),
        migrations.AddField(
            model_name='client',
            name='pays_taxes',
            field=models.BooleanField(default=True, verbose_name='Paga Impuestos?'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='client',
            name='pred_discount',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Descuento Predeterminado'),
        ),
    ]
