# Generated by Django 2.0.1 on 2018-01-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20180129_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Código'),
        ),
    ]
