# Generated by Django 2.0.1 on 2018-01-29 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20180129_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
    ]
