# Generated by Django 2.0.1 on 2018-02-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_auto_20180221_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('GENERAL', 'Cliente General'), ('DISTRIB', 'Distribuidor'), ('WHOLESA', 'Mayorista'), ('WHOLES2', 'Especial')], default='GENERAL', max_length=3, verbose_name='Tipo de Cliente'),
        ),
        migrations.AlterField(
            model_name='client',
            name='id_type',
            field=models.CharField(choices=[('PER', 'Cédula Física'), ('JUR', 'Cédula Jurídica'), ('PAS', 'Pasaporte')], default='PER', max_length=3, verbose_name='Tipo de Identificación'),
        ),
    ]
