# Generated by Django 2.0.1 on 2018-02-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_auto_20180223_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('GENERAL', 'Cliente General'), ('DISTRIB', 'Distribuidor'), ('WHOLESA', 'Mayorista'), ('WHOLES2', 'Especial')], default='GENERAL', max_length=7, verbose_name='Tipo de Cliente'),
        ),
    ]
