# Generated by Django 2.0.1 on 2018-02-23 03:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_auto_20180223_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='Fecha de modificación'),
        ),
    ]
