# Generated by Django 2.0.1 on 2018-02-23 03:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_auto_20180223_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='max_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Descuento Máximo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='max_line_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Descuento Máximo por línea'),
        ),
        migrations.AlterField(
            model_name='client',
            name='pred_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Descuento Predeterminado'),
        ),
    ]
