# Generated by Django 2.0.1 on 2018-02-23 05:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_auto_20180222_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, verbose_name='Límite de Crédito'),
        ),
        migrations.AlterField(
            model_name='client',
            name='max_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Descuento Máximo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='max_line_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Descuento Máximo por línea'),
        ),
        migrations.AlterField(
            model_name='client',
            name='pred_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Descuento Predeterminado'),
        ),
    ]
