# Generated by Django 2.0.1 on 2018-03-01 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180227_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='taxes2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Impuesto2 %'),
        ),
        migrations.AlterField(
            model_name='product',
            name='taxes',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Impuesto %'),
        ),
    ]
