# Generated by Django 2.0.1 on 2018-03-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_fractioned'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_sale_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Descuento Máximo en liquidación %'),
        ),
        migrations.AddField(
            model_name='product',
            name='on_sale',
            field=models.BooleanField(default=False, verbose_name='En liquidación?'),
        ),
    ]
