# Generated by Django 2.0.1 on 2018-03-01 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180228_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_based',
            field=models.BooleanField(default=True, verbose_name='Precio basado en Costo?'),
        ),
    ]
