# Generated by Django 2.0.1 on 2018-03-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_use_taxes2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Precio IVI ₡'),
        ),
        migrations.AddField(
            model_name='product',
            name='sell_price2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Precio IVI ₡'),
        ),
        migrations.AddField(
            model_name='product',
            name='sell_price3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Precio IVI ₡'),
        ),
    ]
