# Generated by Django 2.0.1 on 2018-03-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20180326_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Unidad'),
        ),
    ]
