# Generated by Django 2.0.1 on 2018-04-13 15:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill_number', models.IntegerField(default=1, verbose_name='Número de factura')),
                ('cart', models.TextField(verbose_name='Objeto Carrito')),
                ('client', models.TextField(verbose_name='Objeto Cliente')),
                ('pay', models.TextField(verbose_name='Objeto Pago')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['bill_number'],
            },
        ),
    ]
