# Generated by Django 2.0.1 on 2018-04-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='user',
            field=models.TextField(default='', verbose_name='Objeto Usuario'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='bill_number',
            field=models.IntegerField(default=1, editable=False, verbose_name='Número de factura'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cart',
            field=models.TextField(default='', verbose_name='Objeto Carrito'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='client',
            field=models.TextField(default='', verbose_name='Objeto Cliente'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='pay',
            field=models.TextField(default='', verbose_name='Objeto Pago'),
        ),
    ]
