# Generated by Django 2.0.1 on 2018-04-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20180416_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='bill_number',
            field=models.IntegerField(default=1, verbose_name='Número de factura'),
        ),
    ]
