# Generated by Django 2.0.1 on 2018-04-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20180416_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='client_id',
            field=models.CharField(default='1', editable=False, max_length=255, verbose_name='Id de Cliente'),
        ),
        migrations.AddField(
            model_name='sale',
            name='pay_type',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('CRED', 'Crédito'), ('TRAN', 'Transferencia'), ('OTHE', 'Otro')], default='CASH', max_length=3, verbose_name='Tipo de Pago'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payed',
            field=models.BooleanField(default=False, verbose_name='Pagada'),
        ),
    ]
