# Generated by Django 2.0.1 on 2018-04-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20180417_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='client_id',
            field=models.CharField(default='1', max_length=255, verbose_name='Id de Cliente'),
        ),
    ]
