# Generated by Django 2.0.1 on 2018-04-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20180417_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payed',
            field=models.BooleanField(default=True, verbose_name='Pagada'),
        ),
    ]
