# Generated by Django 2.0.1 on 2018-04-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20180417_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='pay_type',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('CRED', 'Crédito'), ('TRAN', 'Transferencia'), ('OTHE', 'Otro')], default='CASH', max_length=4, verbose_name='Tipo de Pago'),
        ),
    ]
