# Generated by Django 2.0.1 on 2018-04-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_movement',
            name='bill_id',
            field=models.CharField(default='', max_length=255, verbose_name='ID Factura'),
        ),
        migrations.AlterField(
            model_name='credit_movement',
            name='client_id',
            field=models.CharField(default='', max_length=255, verbose_name='ID Objeto Cliente'),
        ),
    ]
