# Generated by Django 2.0.1 on 2018-04-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_auto_20180417_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_movement',
            name='bill_id',
            field=models.CharField(default='', max_length=255, verbose_name='ID Objetov Factura'),
        ),
        migrations.AlterField(
            model_name='credit_movement',
            name='movement_type',
            field=models.CharField(choices=[('CRED', 'Crédito'), ('DEBI', 'Débito')], default='CRED', max_length=4, verbose_name='Tipo de Movimiento'),
        ),
    ]
